name: husky
description: Husky make it easy to manage git hooks for your Dart and Flutter projects. 
version: 0.1.4+1
homepage: https://github.com/hyiso/husky
repository: https://github.com/hyiso/husky

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  args: ^2.3.1
  cli_util: ^0.3.5
  path: ^1.8.0

dev_dependencies:
  commitlint_cli: ^0.2.1
  commitlint_config: ^0.1.1
  lints: ^2.0.0
  test: ^1.17.0
